# Generated by Django 6.0.4 on 2026-04-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menus/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='steps',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
